### ISSUE TITLE
black pill not compatible with PCB design

### ISSUE THREAD

**Issue by ewooonk** [sh969/open-seneca#1]
The pinout of the blue STM32 board mentioned in the components list is not compatible with the PCB design because of the different pin-out and smaller width. This is the right board:

https://www.aliexpress.com/item/Arsmundi-STM32F103C8T6-ARM-STM32-Minimum-System-Development-Board-Module-Micro-USB-controller-ARM-Learning-Board/32970963630.html?

**Comment by sh969** [comment]
PCB v4 and v6 are designed for the Black Pill. Both the Blue Pill and the Black Pill are based on the STM32 but the boards have a slightly different pin layout. In the code you only need to change the onboard LED pin (PB12 for the Black Pill or PC13 for the Blue Pill). If you wanted to build a circuit based on the Blue Pill you can use this pinout for v6:

https://github.com/sh969/CambikeSensor/blob/master/bp_v6/Kenya_prototype_pinout_blue.png
