### ISSUE TITLE
button led connection

### ISSUE THREAD

**Issue by ewooonk** [sh969/open-seneca#2]
The guide is not clear about the button led connection.

Button led pinout (from left to right) connects to
1: Battery GND
2: LoRa GND & SD GND
3: Button pin 2
4: Black Pill A1
5: Black Pill B0
6: Black Pill B1

Typical push button has 5 connectors 
C (common) 
NO (Normally Open circuit) 
NC (Normally Closed circuit)
plus 
minus

When you press the button the circuit should be closed and the button light turns on. Otherwise the circuit is open and the light is turned off.

Configuration??
button - to pin 1 (battery GND)
button + to pin 2 (device GND)
button NO to pin 3 (button +)
button C to battery + (pin ??)
button NC (not connected?)

![Screenshot from 2019-03-21 17-32-40](https://user-images.githubusercontent.com/25252949/54768415-684aff80-4bff-11e9-9bda-57d99abb17d2.png)

**Comment by sh969** [comment]
Thank you for sharing your wiring for the button LED. We also only connect NO (NC is not connected) to power our device when the latching button is closed. I hope everything works for you.
