### ISSUE TITLE
SPS30_getSerialNumber returns 16 null bytes at the end

### ISSUE THREAD

**Issue by drt24** [sh969/open-seneca#4]
I get values rendered like "41766AB7B3D6A7E9^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@" on the serial console and in the CSV file because null (0) bytes are being returned over the wire after the serial number.
I think a null check is required before appending to output:

      for (int i=0; i<48; i++) {
    //    Serial.print(i); Serial.print(": "); Serial.print(SN[i]); Serial.print(" = "); Serial.println(char(SN[i]));
        if (i%3==0) { // 2 ASCII bytes are followed by 1 checksum byte
          output += char(SN[i]);
          output += char(SN[i+1]);
        }
      }

**Comment by sh969** [comment]
Thank you, we will fix this with the next version.
